// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGsFUgayKkrSUMbOHXFvtP1rGV6pg47g',
    appId: '1:46750095275:web:11ae18cc5556cf8565a4ee',
    messagingSenderId: '46750095275',
    projectId: 'nantib1111',
    authDomain: 'nantib1111.firebaseapp.com',
    storageBucket: 'nantib1111.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA61oeQrpEse4WDZhm4G5dZ4sQaBynnSNw',
    appId: '1:46750095275:android:9db42db84aa9f83365a4ee',
    messagingSenderId: '46750095275',
    projectId: 'nantib1111',
    storageBucket: 'nantib1111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxdLq46AFIfKHHUMRRwdtJPLBXGoMyzYc',
    appId: '1:46750095275:ios:6b01336dd4f9b0f165a4ee',
    messagingSenderId: '46750095275',
    projectId: 'nantib1111',
    storageBucket: 'nantib1111.appspot.com',
    iosClientId: '46750095275-uengne1g8e6f0ae50iu0mcq4ue5ks6l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxdLq46AFIfKHHUMRRwdtJPLBXGoMyzYc',
    appId: '1:46750095275:ios:6b01336dd4f9b0f165a4ee',
    messagingSenderId: '46750095275',
    projectId: 'nantib1111',
    storageBucket: 'nantib1111.appspot.com',
    iosClientId: '46750095275-uengne1g8e6f0ae50iu0mcq4ue5ks6l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemonApp',
  );
}
